routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'BerandaController@index');

Route::prefix('admin')->middleware(['auth','oauth:admin'])->group(function(){
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('media','HomeController@media')->name('media.index');
	Route::get('dashboard','HomeController@index');
	Route::resource('category','CategoryController');
	Route::resource('product','ProductController');
	//transaction
	Route::get('transaction','TransactionController@index')->name('transaction.index');
	Route::get('transaction/{code}/{status}','TransactionController@status');
	Route::get('transaction/{code}/detail/data','TransactionController@detail');
	Route::get('transaction/{code}/detail/data/cetak','TransactionController@cetakpdf');
	//users
	Route::get('user','UserController@index')->name('admin.user');
	Route::get('user/status/{id}','UserController@changestatus');
	Route::get('user/add','UserController@create')->name('admin.user.create');
	Route::post('user/add','UserController@store')->name('admin.user.store');
	Route::get('user/edit/{id}','UserController@edit');
	Route::post('user/update','UserController@update');
	Route::get('user/delete/{id}','UserController@delete');

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
	protected $fillable = ['name','slug','parent_id','user_id'];
    function children(){
    	return $this->hasMany('App\Category','parent_id');
    }
    function parent(){
    	return $this->belongsTo('App\Category','parent_id','id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use Alert;
use Illuminate\Support\Facades\Auth;

class CategoryController extends Controller
{
   public function index(){
   	$categorys = Category::where('parent_id',null)->get();
   	return view('admin.category.index',compact('categorys'));
   }
   public function store(Request $request){

   		$category = new Category;
   		$category->slug = $request->slug;
   		$category->name = $request->name;
   		$category->parent_id = $request->parent_id;
   		$category->icon = $request->icon;
   		$category->user_id = Auth::user()->id;
   		$category->save();
   		Alert::success('', 'Category Berhasil di Tambahkan');
   		return redirect('admin/category');
   }
   public function edit(Request $request,$id){
   		$category = Category::find($id);
   		$categorys = Category::where('parent_id',null)->get();
   		return view('admin.category.edit',compact('category','categorys'));
   }
   public function update(Request $request,$id){
   	$category = Category::find($id);
   	$category->slug = $request->slug;
	$category->name = $request->name;
	$category->parent_id = $request->parent_id;
	$category->icon = $request->icon;
	$category->save();
	Alert::success('', 'Category Berhasil di Perbarui');
   	return redirect(route('category.index'));
   }
   public function destroy($id){
   	$category = Category::find($id);
   	$category->delete();
   	Alert::success('', 'Category Berhasil di Delete');
   	return redirect(route('category.index'));
   }
}

resources/views/admin/category/edit.blade.php
@extends('admin.layout.master')
	@section('header')
      <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('static/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
  <style type="text/css">
    .table_list {
      list-style: none;
      padding: 3px;
      margin-left: -30px;
    }
  </style>
  <title>Update Category - Tumbas.id</title>
	@endsection
	@section('body')
  <div class="row">
    <div class="col-md-12">
       <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Update Category</h3>
            </div>
            <form role="form" action="{{ route('category.update',$category->id) }}" method="POST">
            {{ csrf_field() }}
            {{ method_field('PUT')}}
              <div class="box-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Name</label>
                  <input type="text" class="form-control"  placeholder="Enter Category" name="name" value="{{ $category->name }}">
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Slug</label>
                  <input type="text" class="form-control"  placeholder="Enter Slug" name="slug" value="{{ $category->slug }}">
                </div>
                 <div class="form-group">
                  <label for="exampleInputEmail1">Icon</label>
                  <input type="text" class="form-control"  placeholder="Enter Icon Font Awesome" name="icon" value="{{ $category->icon }}">
                </div>
                <div class="form-group">
                      @if($category->parent_id ==null)
                        <input type="hidden" name="parent_id" value="">
                      @else
                       <label for="exampleInputPassword1">Parent Caegory</label>
                       <select class="form-control" name="parent_id">
                          @foreach($categorys as $cas)
                          <option value="{{ $cas->id }}"
                              @if($cas->id == $category->parent_id)
                              selected="selected"
                              @endif
                               >{{ $cas->name }}</option>
                          @endforeach
                         </select>
                      @endif
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
    </div>
  </div>
	@endsection
	@section('footer')
		  <!-- DataTables -->
  <script src="{{ asset('static/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('static/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
  <script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>
	@endsection
@show

resources/views/admin/category/index.blade.php
@extends('admin.layout.master')
	@section('header')
      <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('static/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
  <style type="text/css">
    .table_list {
      list-style: none;
      padding: 4px;
      margin-left: -30px;
    }
  </style>
  <title>Category - Tumbas.id</title>
	@endsection
	@section('body')
  <div class="row">
    <div class="col-md-4">
       <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Add Category</h3>
            </div>
            <form role="form" action="{{ url('admin/category') }}" method="POST">
            {{ csrf_field() }}
              <div class="box-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Name</label>
                  <input type="text" class="form-control"  placeholder="Enter Category" name="name">
                </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Slug</label>
                  <input type="text" class="form-control"  placeholder="Enter Slug" name="slug">
                </div>
                 <div class="form-group">
                  <label for="exampleInputEmail1">Icon</label>
                  <input type="text" class="form-control"  placeholder="Enter Icon Font Awesome" name="icon">
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">Parent Caegory</label>
                  <select class="form-control" name="parent_id">
                     <option value="">Select</option>
                     @foreach($categorys as $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                      @endforeach
                  </select>
                </div>
              </div>
              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
    </div>
    <div class="col-md-8">
       <div class="box">
    <div class="box-header">
      <h3 class="box-title">Category</h3>
    </div>
    <div class="box-body">
      <table id="example1" class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>No</th>
          <th width="400px">Category</th>
          <th>Action</th>
        </tr>
        </thead>
        <tbody>
          @php
              $no = 1;
          @endphp
          @foreach($categorys as $category)
          <tr>
            <td width="40px">{{ $no++ }}</td>
            <td>{{ $category->name }}
              <ul>
                @foreach($category->children as $subcategory)
                   <li class="table_list"> - {{ $subcategory->name }} </li>
                @endforeach
              </ul>
            </td>
            <td>
            <form action="{{ route('category.destroy',$category->id) }}" method="post">
              <a href="{{url('admin/category/'.$category->id.'/edit') }}" class="btn btn-primary  btn-xs">Edit</a>
              {{ csrf_field() }}
              {{ method_field('DELETE')}}
              <input type="submit" name="" value="Delete" class="btn btn-danger  btn-xs">
             </form>
              <ul>
                @foreach($category->children as $subcategory)
                   <form action="{{ route('category.destroy',$subcategory->id) }}" method="post">
                   <li class="table_list"  style="margin-left: -43px"> <a href="{{url('admin/category/'.$subcategory->id.'/edit') }}" class="btn btn-primary  btn-xs">Edit</a>
                        {{ csrf_field() }}
                        {{ method_field('DELETE')}}
                        <input type="submit" name="" value="Delete" class="btn btn-danger btn-xs">
                       </form>
                   </li>
                @endforeach
              </ul>
            </td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>
    <!-- /.box-body -->
    </div>
    </div>
  </div>
	@endsection
	@section('footer')
		  <!-- DataTables -->
  <script src="{{ asset('static/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('static/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
  <script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>
	@endsection
@show